[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures = { workspace = true }
url = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
