[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }