[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
axum = { version= "0.7", features = ["ws"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio-tungstenite = "0.23"
futures = "0.3"
