name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update

      - name: Build server and client
        run: cargo build --bin server --bin client

      - name: Run chat server
        run: |
          cargo run --bin server > server.log 2>&1 &
          sleep 5 # Wait for the server to start

      - name: Run client and send message
        run: |
          echo "Connecting client and sending message..."
          echo -e "send Hello, server!\nleave" | cargo run --bin client 127.0.0.1 3000 testuser

      - name: Ensure no errors in server logs
        run: |
          echo "Checking server logs for errors..."
          if grep -q "error" server.log; then
            echo "Server encountered an error."
            exit 1
          else
            echo "No errors found in server logs."
          fi

      - name: Display server logs
        if: failure()
        run: cat server.log
