name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      chat_server:
        image: rust:latest
        ports:
          - 3000:3000
        options: >-
          --network host

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Build server
        run: cargo build --bin server

      - name: Run chat server
        run: |
          cargo run --bin server &
          sleep 5 # Wait for the server to start

      - name: Run client and send message
        run: |
          echo "Connecting client and sending message..."
          echo -e "send Hello, server!\nleave" | cargo run --bin client 127.0.0.1 3000 testuser

      - name: Ensure no errors
        run: |
          echo "Check logs for errors"
          if grep -q "error" server.log; then
            echo "Server encountered an error."
            exit 1
          fi
